### ISSUE TITLE
Allow overriding the package manager detection

### ISSUE THREAD

**Issue by mattrobenolt** [snyk/snyk#104]
For use in Python projects, it's not strictly required to name your requirements file `requirements.txt` and it's relatively common to have dependencies split across a few different files. In [Sentry](https://github.com/getsentry/sentry) we have 4 different files, `requirements-{base,dev,saml,test}.txt`. And this setup makes it impossible, from what I could see, to run a test over these files. The autodetection bits seem to strictly require it to be named `requirements.txt` without a way to say `--package-manager=pip`

So the ask is for adding a command line argument such that:

```
$ snyk test --file=requirements-base.txt --package-manager=pip
```

becomes a thing. Right now running this results in **Could not detect package manager for file: requirements-base.txt**

**Comment by darscan** [comment]
Hello @mattrobenolt . Thanks for reporting this. Quite right, this is a shortcoming with our current implementation. I can't commit to an official timeline right now, but this is definitely something we need to address.

**Comment by darscan** [comment]
So... bizarrely, and almost certainly unintentionally, right now you can do this:
```
$ snyk test --file=requirements-base.txt --packageManager=pip
```
We should still add this as an official, supported feature with a "lessStrange" flag, but hey, this bug is feature :)

**Comment by mattrobenolt** [comment]
Awesome, that seems to have worked! I'll keep this issue open and I'll follow along for an official support. For now, will move forward with using `--packageManager=pip`.

Thanks!

**Comment by adjogahm** [comment]
Hi guys,
What would be your package-manager flag equivalent for a CircleCI build using your Orb?
I tried this hoping it works without success:
```- snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}'
          severity-threshold: high
          token-variable: SNYK_TOKEN
          target-file: requirements-locked.txt
          package-manager: pip
```
And I can't find anything in documentation. It seems the Orb doesn't support it yet.

**Comment by punkdata** [comment]
> Hi guys,
> What would be your package-manager flag equivalent for a CircleCI build using your Orb?
> I tried this hoping it works without success:
> 
> ```
> - snyk/scan:
>           fail-on-issues: false
>           monitor-on-build: true
>           project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}'
>           severity-threshold: high
>           token-variable: SNYK_TOKEN
>           target-file: requirements-locked.txt
>           package-manager: pip
> ```
> 
> And I can't find anything in documentation. It seems the Orb doesn't support it yet.

Try the `additional-arguments` parameter with the cli flag:

```
- snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}'
          severity-threshold: high
          token-variable: SNYK_TOKEN
          target-file: requirements-locked.txt
          additional-arguments: "--packageManager=pip"
```
