### ISSUE TITLE
[🐛] .snyk file is ignored using docker image

### ISSUE THREAD

**Issue by gbrandalise** [snyk/snyk#1164]
- OS: Windows
- Command run: docker run --rm -e "SNYK_TOKEN=<SNYK_TOKEN>" -v "/var/run/docker.sock:/var/run/docker.sock" -v $pwd/devops/dev/Dockerfile:/project/Dockerfile -v $pwd/.snyk:/project/.snyk snyk/snyk:docker snyk test --file=/project/Dockerfile --docker <IMAGE_NAME>

### Expected behaviour
Vulnerabilities present in the .snyk file were ignored.

### Actual behaviour
.snyk file isn't used in the test.

### Steps to reproduce
Create a .snyk file with vulnerabilities ignored and use it to test a docker image with these vulnerabilities.

**Comment by lili2311** [comment]
👋 This is intentional behaviour you can run the docker scan from anywhere, please point to the specific policy you want with `--policy-path=path/to/folder/.snyk`

As referenced in the snyk help docs 
```  $ snyk test --docker app:latest --file=Dockerfile --policy-path=path/to/.snyk
```

**Comment by gbrandalise** [comment]
Thanks for your help @lili2311 , but it still doesn't work. 
Does the folder where the .snyk file is located refer to the container or host directory?

I did it this way:
`docker run --rm -e "SNYK_TOKEN=<SNYK_TOKEN>" -v "/var/run/docker.sock:/var/run/docker.sock" -v $pwd/devops/dev/Dockerfile:/project/Dockerfile -v $pwd/.snyk:/project/.snyk snyk/snyk:docker snyk test --file=/project/Dockerfile --docker <IMAGE_NAME> --policy-path=/project/.snyk`

But it ignores the .snyk file

**Comment by garethr** [comment]
I did a bit of investigation here. I've pinned this down to an issue in the linux executables for Snyk from https://github.com/snyk/snyk/releases. This is definitely present in the latest release and in the v1.346.0 in use in the images.

```
./snyk-linux test --docker alpine:3.10.0 --policy-file=.snyk
```

Used with the following ignore file:

```
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.14.1
# ignores vulnerabilities until expiry date; change duration by modifying expiry date
ignore:
  SNYK-ALPINE310-MUSL-458452:
    - '*':
        reason: None Given
        expires: 2020-07-23T11:52:25.612Z
patch: {}
```

This vulnerability will not be ignored due to this bug.
