### ISSUE TITLE
Could not detect supported target files. Snyk CLI doesnt see to work out of the box :/

### ISSUE THREAD

**Issue by rdagumampan** [snyk/snyk#1313]
Hi Snyk Team,

I'm trying to use this to one our .NET Core 3.1 solution and to my surprised it doesn't work out of the box. I at least was expecting the CLI tool will recursively detect project files and solution files that can be analyzed but I keep on getting this error.

```
Starting: sudo snyk test
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/9bc347f9-5c89-4b42-94e7-b17cd8a11692.sh
Could not detect supported target files in Harmonizer.Test, Harmonizer, Shared, DataGenerator, Shared.Test, DataGenerator.Test, MockedContextService, MockedContextService.Test, TestConfigurationGenerator, GoldDataInterface, SignalRTestApp.
Please see our documentation for supported languages and target files: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support and make sure you are in the right directory.


##[error]Bash exited with code '2'.
Finishing: sudo snyk test
```

Yaml
```yaml
trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      sudo npm install -g snyk

      # create variable in Pipelines called 'SNYK_TOKEN' and securely save your Snyk token value
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables

      sudo snyk auth $(SNYK_TOKEN)
    displayName: 'install snyk'

  - script: |
      # sudo snyk test --all-projects
      sudo snyk test --file=OAI.sln
    displayName: 'sudo snyk test'
```
