### ISSUE TITLE
[🐛] Cannot find module 'legacy-snyk-docker-plugin'

### ISSUE THREAD

**Issue by orsinium** [snyk/snyk#1453]
- `node -v`: `10.21.0`
- `npm -v`: -
- `snyk -v`: `1.413.0 `
- OS: debian buster
- Command run: `snyk auth $SNYK_TOKEN`

### Expected behaviour

It works on Snyk 1.411.0 without exceptions but fails on 1.413.0.

### Actual behaviour

```
$ npm install -g snyk
/usr/local/bin/snyk -> /usr/local/lib/node_modules/snyk/dist/cli/index.js
+ snyk@1.413.0
added 451 packages from 327 contributors in 44.743s
$ snyk auth $SNYK_TOKEN
Error: Cannot find module 'legacy-snyk-docker-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/src/lib/plugins/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Steps to reproduce

Gitlab CI job:

```
snyk:
  image: "python:3.6-buster"
  before_script:
    - cp -r ./venv $VENV_PATH
    - apt-get update
    - apt-get install -y -q nodejs npm
    - npm install -g snyk
    - snyk auth $SNYK_TOKEN
```

### Debug log

-

### Screenshots

![image](https://user-images.githubusercontent.com/9638362/95585124-136c1580-0a3f-11eb-85e9-3ad0462c79fd.png)
