### ISSUE TITLE
Support: Bitbucket Cloud

### ISSUE THREAD

**Issue by gonace** [snyk/snyk#149]
Since Gemnasium is closing on May 15th it would be awesome to see snyk take the advantage to support Bitbucket Cloud. Since there are no real alterantive when using Bitbucket Cloud :(

Regards

**Comment by Zabanya** [comment]
use pipelines for now

```
        - step:
            name: Snyk Vulnerability Test
            image: snyk/snyk-cli:npm
            script:
            - snyk auth ${SNYK_TOKEN} -d --org=xyz
            - snyk test --org=xyz
            - snyk test --org=xyz --file=composer.lock

```
