### ISSUE TITLE
Snyk is sending notifications of ignored, non expired vulnerabilities

### ISSUE THREAD

**Issue by aviggiano** [snyk/snyk#151]
- `node -v`: v8.9.4
- `npm -v`: 5.6.0
- `snyk -v`: 1.73.0
- Command run: `snyk monitor`

### Expected behaviour

Snyk should not send slack notifications when a vulnerability is set to `ignored`, unless a new upgrade/patch has being issued, or unless the vulnerability has expired 

### Actual behaviour

Snyk is sending slack notifications for `ignored`, non expired, non updated vulnerabilities.

![snyk-notification](https://user-images.githubusercontent.com/3029017/39265383-8129e108-489d-11e8-94fa-d4d9507e0ad4.png)

This notification sends me to the following URL: https://snyk.io/vuln/npm:hoek:20180212?utm_source=slack

But the `npm:hoek:20180212` vulnerability is being ignored by my `.snyk` file:

```
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.11.0
# ignores vulnerabilities until expiry date; change duration by modifying expiry date
ignore:
...
  'npm:hoek:20180212':
    - my-project-1 > winston-loggly > loggly > request > hawk > hoek:
        reason: None given
        expires: '2018-05-25T17:58:02.567Z'
...
patch: {}
```

### Steps to reproduce

1. Setup snyk on a project
2. Integrate snyk with slack webhooks
3. Run `snyk monitor` after `snyk test` on a continuous integration environment (I am using Circle CI)
