### ISSUE TITLE
`snyk test` detects new vulnerability right after running `snyk wizard`

### ISSUE THREAD

**Issue by aviggiano** [snyk/snyk#153]
- `node -v`: v8.9.1
- `npm -v`: 5.5.1
- `snyk -v`: 1.73.0
- Command run: `snyk test`

### Expected behaviour

`snyk test` should not detect vulnerabilities that have just been addressed by `snyk wizard`

### Actual behaviour

`snyk test` finds a new vulnerability that was not identified by `snyk wizard`. 

### Steps to reproduce

1. Run `snyk wizard` and "Ignore" all vulnerabilities
2. Run `snyk test`

---

Step 1
```
$ snyk wizard

Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

Analyzing npm dependencies for package.json
Querying vulnerabilities database...
Tested 335 dependencies for known vulnerabilities, found 5 vulnerabilities, 9 vulnerable paths.

? Low severity vuln found in braces@1.8.5, introduced via babel-cli@6.26.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: babel-cli@6.26.0 > chokidar@1.7.0 > anymatch@1.3.2 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

? Low severity vuln found in hoek@2.16.3, introduced via boom@2.10.1
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:hoek:20180212
- from: boom@2.10.1 > hoek@2.16.3
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

? Low severity vuln found in hoek@2.16.3, introduced via my-private-repo@1.0.0
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:hoek:20180212
- from: my-private-repo@1.0.0 > winston-loggly@1.3.1 > loggly@1.1.1 > request@2.75.0 > hawk@3.1.3 > hoek@2.16.3
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

? Low severity vuln found in hoek@2.16.3, introduced via my-private-repo@1.0.0
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:hoek:20180212
- from: my-private-repo@1.0.0 > winston-loggly@1.3.1 > loggly@1.1.1 > request@2.75.0 > hawk@3.1.3 > boom@2.10.1 > hoek@2.16.3
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

? Low severity vuln found in hoek@2.16.3, introduced via my-private-repo@1.0.0
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:hoek:20180212
- from: my-private-repo@1.0.0 > winston-loggly@1.3.1 > loggly@1.1.1 > request@2.75.0 > hawk@3.1.3 > sntp@1.0.9 > hoek@2.16.3
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

? Low severity vuln found in hoek@2.16.3, introduced via my-private-repo@1.0.0
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:hoek:20180212
- from: my-private-repo@1.0.0 > winston-loggly@1.3.1 > loggly@1.1.1 > request@2.75.0 > hawk@3.1.3 > cryptiles@2.0.5 > boom@2.10.1 > hoek@2.16.3
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

? High severity vuln found in timespan@2.3.0, introduced via my-private-repo@1.0.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:timespan:20170907
- from: my-private-repo@1.0.0 > winston-loggly@1.3.1 > loggly@1.1.1 > timespan@2.3.0
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

? Medium severity vuln found in tunnel-agent@0.4.3, introduced via my-private-repo@1.0.0
- desc: Uninitialized Memory Exposure
- info: https://snyk.io/vuln/npm:tunnel-agent:20170305
- from: my-private-repo@1.0.0 > winston-loggly@1.3.1 > loggly@1.1.1 > request@2.75.0 > tunnel-agent@0.4.3
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given
? Add `snyk test` to package.json file to fail test on newly disclosed vulnerabilities?
This will require authentication via `snyk auth` when running tests. Yes
Saving .snyk policy file...
Adding Snyk to devDependencies (used by npm test)
Remembering current dependencies for future notifications...

Your policy file has been created with the actions you've selected, add it to your source control (`git add .snyk`).
To review your policy, run `snyk policy`.

You can see a snapshot of your dependencies here:
https://snyk.io/org/aviggiano/monitor/2c3cee6f-ce66-49d1-8669-1b670a957c28

We'll notify you when relevant new vulnerabilities are disclosed.
```

Step 2
```
$ snyk test

Testing /home/antonio/repo...
✗ High severity vulnerability found on sshpk@1.13.1
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:sshpk:20180409
- from: private-project-A@1.1.7 > private-project-B@1.0.0 > winston-loggly@1.3.1 > loggly@1.1.1 > request@2.75.0 > http-signature@1.1.1 > sshpk@1.13.1
Your dependencies are out of date, otherwise you would be using a newer sshpk than sshpk@1.13.1.
Try deleting node_modules, reinstalling and running `snyk test` again.
If the problem persists, one of your dependencies may be bundling outdated modules.

Organisation: aviggiano
Package manager: npm
Target file: package.json
Open source: no
Local Snyk policy found

Tested 335 dependencies for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.

Run `snyk wizard` to address these issues.
```

`.snyk` file
```
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.11.0
# ignores vulnerabilities until expiry date; change duration by modifying expiry date
ignore:
  'npm:braces:20180219':
    - babel-cli > chokidar > anymatch > micromatch > braces:
        reason: None given
        expires: '2018-05-26T12:16:55.840Z'
  'npm:hoek:20180212':
    - boom > hoek:
        reason: None given
        expires: '2018-05-26T12:16:55.841Z'
    - private-project-B > winston-loggly > loggly > request > hawk > hoek:
        reason: None given
        expires: '2018-05-26T12:16:55.842Z'
    - private-project-B > winston-loggly > loggly > request > hawk > boom > hoek:
        reason: None given
        expires: '2018-05-26T12:16:55.843Z'
    - private-project-B > winston-loggly > loggly > request > hawk > sntp > hoek:
        reason: None given
        expires: '2018-05-26T12:16:55.843Z'
    - private-project-B > winston-loggly > loggly > request > hawk > cryptiles > boom > hoek:
        reason: None given
        expires: '2018-05-26T12:16:55.843Z'
  'npm:timespan:20170907':
    - private-project-B > winston-loggly > loggly > timespan:
        reason: None given
        expires: '2018-05-26T12:16:55.843Z'
  'npm:tunnel-agent:20170305':
    - private-project-B > winston-loggly > loggly > request > tunnel-agent:
        reason: None given
        expires: '2018-05-26T12:16:55.843Z'
patch: {}
```

I'm not sure if that helps, but the structure of my project is as follows:
- repo (private)
  - private-project-A (private)
    - private-project-B (private)
      - [open source projects]
        - vulnerability found by `snyk test`
