### ISSUE TITLE
Add strict policy mode

### ISSUE THREAD

**Issue by dominykas** [snyk/snyk#360]
### Expected behaviour

Have a `--strict-policy` mode, where `expires` and `reason` cannot be left empty.

`snyk` CLI should validate the YAML, to see that it has all the required entries, and that it has no superfluous entries.

### Actual behaviour

A mistake in the policy YAML can disable the expiry of ignored entries.

### Steps to reproduce

Suppose you have the following `.snyk` policy:

```
ignore:
  SNYK-JS-PASSPORTSAML-72411:
    - passport-saml-metadata > passport-saml:
      reason: 'We only use passport-saml-metadata to read SAML XML metadatafile and we are therefore not exposed to that vulnerability'
      expires: '2019-03-31T00:00:00.000Z'
```

It has a bug. See if you can spot it.

Good job - yes, there is white space missing before `reason` and `expires` - the correct yaml would look like so:

```
ignore:
  SNYK-JS-PASSPORTSAML-72411:
    - passport-saml-metadata > passport-saml:
        reason: 'We only use passport-saml-metadata to read SAML XML metadatafile and we are therefore not exposed to that vulnerability'
        expires: '2019-03-31T00:00:00.000Z'
```

With the broken YAML, the ignore would never expire, because `js-yaml` (correctly?) does not see the `expires` date for the `passport-saml-metadata > passport-saml` entry, compare:

Broken:
```
{
  "ignore": {
    "SNYK-JS-PASSPORTSAML-72411": [
      {
        "passport-saml-metadata > passport-saml": null,
        "reason": "We only use passport-saml-metadata to read SAML XML metadatafile and we are therefore not exposed to that vulnerability",
        "expires": "2019-03-31T00:00:00.000Z"
      }
    ]
  }
}
```

Correct:

```
{
  "ignore": {
    "SNYK-JS-PASSPORTSAML-72411": [
      {
        "passport-saml-metadata > passport-saml": {
          "reason": "We only use passport-saml-metadata to read SAML XML metadatafile and we are therefore not exposed to that vulnerability",
          "expires": "2019-03-31T00:00:00.000Z"
        }
      }
    ]
  }
}
```

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.
