### ISSUE TITLE
snyk wizard appears to effect changes but snyk test shows no improvement

### ISSUE THREAD

**Issue by martinhbramwell** [snyk/snyk#688]
- `node -v`:  v11.11.0
- `npm -v`: 6.7.0
- `snyk -v`: 1.199.2
- Command run: `snyk test` then `snyk wizard` then `snyk test`

### Expected behaviour
Expect fewer vulnerabilities after running `snyk wizard`

### Actual behaviour
After running `snyk wizard`, `snyk test` shows same vulnerabilities as before.
#### First Test Result
```
Package manager:   npm
Target file:       package-lock.json
Local Snyk policy: found

Tested 959 dependencies for known vulnerabilities, found 5 vulnerabilities, 242 vulnerable paths.

Run 'snyk wizard' to address these issues.
```

#### Wizard Result

```
snyk wizard

Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

? Existing .snyk policy found. Ignore it and start from scratch [y] or update it [N]? Yes
Analyzing npm dependencies for /home/you/services/vue-offlinefirst-spa-pwa/packages/lambdaSrv
Analyzing npm dependencies for lambdaSrv project dir
Querying vulnerabilities database...
Tested 937 dependencies for known vulnerabilities, found 4 vulnerabilities, 240 vulnerable paths.

? ✗ 46 High vulnerabilities introduced via babel-cli@6.26.0
    Info: https://snyk.io/package/npm/babel-cli/6.26.0

  Remediation options Re-install babel-cli@6.26.0

? ✗ 12 High vulnerabilities introduced via babel-plugin-transform-class-properties@6.24.1
    Info: https://snyk.io/package/npm/babel-plugin-transform-class-properties/6.24.1

  Remediation options Re-install babel-plugin-transform-class-properties@6.24.1

? ✗ 137 High vulnerabilities introduced via babel-preset-env@1.7.0
    Info: https://snyk.io/package/npm/babel-preset-env/1.7.0

  Remediation options Re-install babel-preset-env@1.7.0

? ✗ 33 High vulnerabilities introduced via chokidar@2.0.4
    Info: https://snyk.io/package/npm/chokidar/2.0.4

  Remediation options Re-install chokidar@2.0.4

? ✗ High severity vuln found in lodash@4.17.11, introduced via cypress@3.1.5
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-LODASH-450202
    From: cypress@3.1.5 > getos@3.1.0 > async@2.4.0 > lodash@4.17.11

  Remediation options Re-install cypress@3.1.5

? ✗ 3 High vulnerabilities introduced via pug@2.0.3
    Info: https://snyk.io/package/npm/pug/2.0.3

  Remediation options Re-install pug@2.0.3

? ✗ 5 High vulnerabilities introduced via snyk@1.199.2
    Info: https://snyk.io/package/npm/snyk/1.199.2

  Remediation options Re-install snyk@1.199.2

? ✗ High severity vuln found in lodash@4.17.11, introduced via winston@3.1.0
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-LODASH-450202
    From: winston@3.1.0 > async@2.6.1 > lodash@4.17.11

  Remediation options Re-install winston@3.1.0

? ✗ High severity vuln found in lodash@4.17.11, introduced via cypress@3.1.5
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-LODASH-450202
    From: cypress@3.1.5 > lodash@4.17.11

  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None available

? ✗ Low severity vuln found in braces@1.8.5, introduced via babel-cli@6.26.0
    Description: Regular Expression Denial of Service (ReDoS)
    Info: https://snyk.io/vuln/npm:braces:20180219
    From: babel-cli@6.26.0 > chokidar@1.7.0 > anymatch@1.3.2 > micromatch@2.3.11 > braces@1.8.5

  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None available
Applying updates using npm...
Saving .snyk policy file...
Updating package.json...
Remembering current dependencies for future notifications...

Your .snyk policy file has been successfully updated.
To review your policy, run `snyk policy`.

You can see a snapshot of your dependencies here:
https://snyk.io/org/martinhbramwell/monitor/bcae1852-55b0-48b0-98c5-834be7cc46b9

We'll notify you when relevant new vulnerabilities are disclosed.


\ Analyzing npm dependencies for /home/you/services/vue-offlinefirst-spa-pwa/packages/lambdaSrv/package-lock.json
```

#### Second Test Result
```
Package manager:   npm
Target file:       package-lock.json
Local Snyk policy: found

Tested 959 dependencies for known vulnerabilities, found 5 vulnerabilities, 242 vulnerable paths.

Run 'snyk wizard' to address these issues.
```
#### Policy File

```
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.13.5
# ignores vulnerabilities until expiry date; change duration by modifying expiry date
ignore:
  'npm:braces:20180219':
    - babel-cli > chokidar > anymatch > micromatch > braces:
        reason: None available
        expires: '2019-08-24T14:56:04.363Z'
  SNYK-JS-LODASH-450202:
    - cypress > lodash:
        reason: None available
        expires: '2019-08-24T14:56:04.363Z'
# patches apply the minimum changes required to fix a vulnerability
patch:
  SNYK-JS-LODASH-450202:
    - cypress > lodash:
        patched: '2019-07-25T13:58:55.707Z'
```

### Steps to reproduce
Run commands : `snyk test` then `snyk wizard` then `snyk test`

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

### Debug Gist
https://gist.github.com/martinhbramwell/11540118084454aa0a6a596611363aa7
