### ISSUE TITLE
Bug: snyk wizard unexpectedly adds snyk as dependency in package.json

### ISSUE THREAD

**Issue by wheresrhys** [snyk/snyk#938]
- `node -v`: v12.13.1
- `npm -v`: 6.13.2
- `snyk -v`: 1.269.0. Upgraded to 1.272.0 and the problem persists
- Command run: `snyk wizard`

### Expected behaviour
Run snyk wizard using globally installed snyk, but not add snyk as a local project dependency

### Actual behaviour
snyk is added to `dependencies` in package.json. 

It also doesn't seem to apply the patch it says it will, and the .snyk file appears stuck in an old state, as follows:
```
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.13.5
# ignores vulnerabilities until expiry date; change duration by modifying expiry date
ignore:
  SNYK-JS-AUTOLINKER-73494:
    - autolinker:
        reason: None given
        expires: '2019-02-21T18:08:23.436Z'
  'npm:mem:20180117':
    - showdown > yargs > os-locale > mem:
        reason: no fix available
        expires: '2019-12-25T11:40:57.014Z'
  SNYK-JS-AXIOS-174505:
    - googleapis > google-auth-library > axios:
        reason: breaking changes in v37
        expires: '2019-06-30T10:32:53.965Z'
    - googleapis > google-auth-library > gcp-metadata > axios:
        reason: breaking changes in v37
        expires: '2019-06-30T10:32:53.965Z'
  SNYK-JS-HTTPSPROXYAGENT-469131:
    - googleapis > google-auth-library > gtoken > gaxios > https-proxy-agent:
        reason: no fix available
        expires: '2019-12-25T12:02:02.294Z'
    - snyk > proxy-agent > pac-proxy-agent > https-proxy-agent:
        reason: None given
        expires: '2019-11-21T12:24:46.045Z'
    - snyk > proxy-agent > https-proxy-agent:
        reason: None given
        expires: '2019-11-21T12:24:46.045Z'
  SNYK-JS-SHOWDOWN-469487:
    - showdown:
        reason: no remediation available
        expires: '2019-11-21T12:20:45.283Z'
SNYK-JS-HTTPSPROXYAGENT-469131:
  - googleapis > google-auth-library > gtoken > gaxios > https-proxy-agent:
      reason: breaking changes in v37
      expires: '2020-01-12T12:05:10.000Z'
# patches apply the minimum changes required to fix a vulnerability
patch:
  SNYK-JS-LODASH-450202:
    - '@financial-times/biz-ops-schema > lodash':
        patched: '2019-07-08T13:03:18.462Z'
    - elasticsearch > lodash:
        patched: '2019-07-08T13:03:18.462Z'
    - archiver > async > lodash:
        patched: '2019-07-08T13:03:18.462Z'
    - lodash:
        patched: '2019-07-08T13:03:18.462Z'
    - snyk > snyk-config > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > snyk-mvn-plugin > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > snyk-go-plugin > graphlib > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > snyk-nodejs-lockfile-parser > graphlib > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > snyk-php-plugin > @snyk/composer-lockfile-parser > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > @snyk/dep-graph > graphlib > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > snyk-nodejs-lockfile-parser > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > @snyk/dep-graph > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > snyk-nuget-plugin > lodash:
        patched: '2019-07-08T13:08:55.850Z'
    - snyk > inquirer > lodash:
        patched: '2019-07-08T13:08:55.850Z'
  SNYK-JS-HTTPSPROXYAGENT-469131:
    - googleapis > google-auth-library > gtoken > gaxios > https-proxy-agent:
        patched: '2019-11-25T12:00:35.593Z'
```

### Steps to reproduce
Run snyk wizard in a project without snyk as a local dependency. Choose dfault at each stage of the wizard

---

```
$ snyk wizard --debug
  snyk wizard { _: [ [Circular] ], debug: true } +0ms
  snyk ~~~~ LIVE RUN ~~~~ +0ms
  snyk sending request to: https://snyk.io/api/v1/verify/token +0ms
  snyk request body size: 46 +0ms
  snyk gzipped request body size: 66 +1ms
  snyk not using proxy +0ms
  snyk not using proxy +740ms

Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

? Existing .snyk policy found. Ignore it and start from scratch [y] or update it [N]? No
Analyzing npm dependencies for /Users/wheresrhys/Projects/biz-ops-runbooks
  snyk policies found [ncies for biz-ops-runbooks project dir
  '/Users/wheresrhys/Projects/biz-ops-runbooks',
  '/Users/wheresrhys/Projects/biz-ops-runbooks/node_modules/serverless-offline-sts'
] +0ms
  snyk converting dep-tree to dep-graph { name: 'biz-ops-runbooks', targetFile: 'package-lock.json' } +106ms
  snyk done converting dep-tree to dep-graph { uniquePkgsCount: 292 } +74ms
Analyzing npm dependencies for biz-ops-runbooks project dir
  snyk sending request to: https://snyk.io/api/v1/test-dep-graph +46s
  snyk request body size: 57158 +0ms
  snyk gzipped request body size: 9350 +0ms
  snyk not using proxy +4ms
Querying vulnerabilities database...
Tested 291 dependencies for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.
  snyk starting questions +50s
  snyk getUpdatePrompts +0ms

  snyk final show SNYK-JS-HTTPSPROXYAGENT-469131 when {
  when: [Function: when],
  name: 'SNYK-JS-HTTPSPROXYAGENT-469131-u0',
  type: 'list',
  message: '\u001b[1m\u001b[33m✗ Medium severity vuln found in https-proxy-agent@2.2.2, introduced via googleapis@27.0.0\u001b[39m\u001b[22m\n' +
    '    Description: Man-in-the-Middle (MitM)\n' +
    '    Info: \u001b[4mhttps://snyk.io\u001b[24m\u001b[4m/vuln/SNYK-JS-HTTPSPROXYAGENT-469131\u001b[24m\n' +
    '    From: googleapis@27.0.0 > google-auth-library@1.6.1 > gtoken@2.3.3 > gaxios@1.8.4 > https-proxy-agent@2.2.2\n' +
    '\u001b[32m\u001b[39m\n' +
    '\u001b[32m  Remediation options\u001b[39m',
  patches: [Object],
  default: 0,
  choices: [Array],
  vuln: [Object]
} +11ms
? ✗ Medium severity vuln found in https-proxy-agent@2.2.2, introduced via googleapis@27.0.0
    Description: Man-in-the-Middle (MitM)
    Info: https://snyk.io/vuln/SNYK-JS-HTTPSPROXYAGENT-469131
    From: googleapis@27.0.0 > google-auth-library@1.6.1 > gtoken@2.3.3 > gaxios@1.8.4 > https-proxy-agent@2.2.2

  Remediation options Re-install googleapis@27.0.0
  snyk getPatchPrompts +34s
  snyk getIgnorePrompts +3ms
? Add `snyk test` to package.json file to fail test on newly disclosed vulnerabilities?
This will require authentication via `snyk auth` when running tests. No
  snyk {
  snyk   ignore: [],
  snyk   update: [
  snyk     {
  snyk       CVSSv3: 'CVSS:3.0/AV:A/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N/E:P/RL:U/RC:C',
  snyk       alternativeIds: [],
  snyk       creationTime: '2019-09-26T10:01:07.677036Z',
  snyk       cvssScore: 6.1,
  snyk       disclosureTime: '2019-09-25T08:21:57Z',
  snyk       exploit: 'Proof of Concept',
  snyk       fixedIn: [Array],
  snyk       functions: [],
  snyk       functions_new: [],
  snyk       id: 'SNYK-JS-HTTPSPROXYAGENT-469131',
  snyk       identifiers: [Object],
  snyk       language: 'js',
  snyk       modificationTime: '2019-10-23T09:58:05.142531Z',
  snyk       moduleName: 'https-proxy-agent',
  snyk       packageManager: 'npm',
  snyk       packageName: 'https-proxy-agent',
  snyk       patches: [Array],
  snyk       publicationTime: '2019-10-02T08:08:11Z',
  snyk       references: [Array],
  snyk       semver: [Object],
  snyk       severity: 'medium',
  snyk       title: 'Man-in-the-Middle (MitM)',
  snyk       from: [Array],
  snyk       upgradePath: [Array],
  snyk       isUpgradable: true,
  snyk       isPatchable: true,
  snyk       name: 'https-proxy-agent',
  snyk       version: '2.2.2',
  snyk       nearestFixedInVersion: undefined,
  snyk       __filename: '/Users/wheresrhys/Projects/biz-ops-runbooks/node_modules/https-proxy-agent/package.json',
  snyk       shrinkwrap: undefined,
  snyk       bundled: undefined,
  snyk       parentDepType: 'prod'
  snyk     }
  snyk   ],
  snyk   patch: [],
  snyk   skip: []
  snyk } +38s
  snyk to upgrade { prod: [ 'googleapis@27.0.0' ] } +0ms
  snyk to uninstall [ 'googleapis' ] +0ms
  snyk /Users/wheresrhys/Projects/biz-ops-runbooks$ npm uninstall --save googleapis +0ms
  snyk npm uninstall --save complete +12s
  snyk /Users/wheresrhys/Projects/biz-ops-runbooks$ npm install --save googleapis@27.0.0 +3ms
  snyk npm install --save complete +22s
Applying updates using npm...
  snyk {
  snyk   "version": "v1.13.5",
  snyk   "ignore": {
  snyk     "SNYK-JS-AUTOLINKER-73494": [
  snyk       {
  snyk         "autolinker": {
  snyk           "reason": "None given",
  snyk           "expires": "2019-02-21T18:08:23.436Z"
  snyk         }
  snyk       }
  snyk     ],
  snyk     "npm:mem:20180117": [
  snyk       {
  snyk         "showdown > yargs > os-locale > mem": {
  snyk           "reason": "no fix available",
  snyk           "expires": "2019-12-25T11:40:57.014Z"
  snyk         }
  snyk       }
  snyk     ],
  snyk     "SNYK-JS-AXIOS-174505": [
  snyk       {
  snyk         "googleapis > google-auth-library > axios": {
  snyk           "reason": "breaking changes in v37",
  snyk           "expires": "2019-06-30T10:32:53.965Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "googleapis > google-auth-library > gcp-metadata > axios": {
  snyk           "reason": "breaking changes in v37",
  snyk           "expires": "2019-06-30T10:32:53.965Z"
  snyk         }
  snyk       }
  snyk     ],
  snyk     "SNYK-JS-HTTPSPROXYAGENT-469131": [
  snyk       {
  snyk         "googleapis > google-auth-library > gtoken > gaxios > https-proxy-agent": {
  snyk           "reason": "no fix available",
  snyk           "expires": "2019-12-25T12:02:02.294Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > proxy-agent > pac-proxy-agent > https-proxy-agent": {
  snyk           "reason": "None given",
  snyk           "expires": "2019-11-21T12:24:46.045Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > proxy-agent > https-proxy-agent": {
  snyk           "reason": "None given",
  snyk           "expires": "2019-11-21T12:24:46.045Z"
  snyk         }
  snyk       }
  snyk     ],
  snyk     "SNYK-JS-SHOWDOWN-469487": [
  snyk       {
  snyk         "showdown": {
  snyk           "reason": "no remediation available",
  snyk           "expires": "2019-11-21T12:20:45.283Z"
  snyk         }
  snyk       }
  snyk     ]
  snyk   },
  snyk   "SNYK-JS-HTTPSPROXYAGENT-469131": [
  snyk     {
  snyk       "googleapis > google-auth-library > gtoken > gaxios > https-proxy-agent": {
  snyk         "reason": "breaking changes in v37",
  snyk         "expires": "2020-01-12T12:05:10.000Z"
  snyk       }
  snyk     }
  snyk   ],
  snyk   "patch": {
  snyk     "SNYK-JS-LODASH-450202": [
  snyk       {
  snyk         "@financial-times/biz-ops-schema > lodash": {
  snyk           "patched": "2019-07-08T13:03:18.462Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "elasticsearch > lodash": {
  snyk           "patched": "2019-07-08T13:03:18.462Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "archiver > async > lodash": {
  snyk           "patched": "2019-07-08T13:03:18.462Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "lodash": {
  snyk           "patched": "2019-07-08T13:03:18.462Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > snyk-config > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > snyk-mvn-plugin > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > snyk-go-plugin > graphlib > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > snyk-nodejs-lockfile-parser > graphlib > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > snyk-php-plugin > @snyk/composer-lockfile-parser > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > @snyk/dep-graph > graphlib > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > snyk-nodejs-lockfile-parser > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > @snyk/dep-graph > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > snyk-nuget-plugin > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       },
  snyk       {
  snyk         "snyk > inquirer > lodash": {
  snyk           "patched": "2019-07-08T13:08:55.850Z"
  snyk         }
  snyk       }
  snyk     ],
  snyk     "SNYK-JS-HTTPSPROXYAGENT-469131": [
  snyk       {
  snyk         "googleapis > google-auth-library > gtoken > gaxios > https-proxy-agent": {
  snyk           "patched": "2019-11-25T12:00:35.593Z"
  snyk         }
  snyk       }
  snyk     ]
  snyk   },
  snyk   "__modified": "2020-01-03T17:30:02.911Z",
  snyk   "__created": "2020-01-03T16:54:34.162Z",
  snyk   "__filename": ".snyk"
  snyk } +0ms
Saving .snyk policy file...
  snyk snyk version: 1.272.0 +34s
  snyk /Users/wheresrhys/Projects/biz-ops-runbooks$ npm install --save snyk +489ms
  snyk npm install --save complete +27s
Updating package.json...
  snyk running monitor +27s
  snyk Analyzing npm dependencies for /Users/wheresrhys/Projects/biz-ops-runbooks/package-lock.json +0ms
  snyk not using proxy +2m
  snyk Org financial-times doesn't have 'experimental-dep-graph' feature enabled +0mslock.json
  snyk sending request to: https://snyk.io/api/v1/monitor/npm +2sps-runbooks/package-lock.json
  snyk request body size: 125528 +0ms
  snyk gzipped request body size: 10035 +1ms
  snyk not using proxy +0ms
Remembering current dependencies for future notifications...

Your .snyk policy file has been successfully updated.
To review your policy, run `snyk policy`.

You can see a snapshot of your dependencies here:
https://snyk.io/org/financial-times/monitor/715eddb9-a33d-4c2c-81d0-0452ca8a1e71

We'll notify you when relevant new vulnerabilities are disclosed.


  snyk analytics {
  args: [
    {
      debug: true,
      org: null,
      ignoreDisabled: false,
      traverseNodeModules: false,
      packageManager: 'npm',
      file: 'package-lock.json',
      projectNames: [Array],
      packageLeading: '',
      packageTrailing: ''
    }
  ],
  command: 'wizard',
  org: null,
  metadata: {
    payloadSize: [ 46, 57158, 125528 ],
    gzippedPayloadSize: [ 66, 9350, 10035 ],
    'inline-auth': false,
    'start-over': false,
    local: [ true, true, true ],
    'generating-node-dependency-tree': [ [Object], [Object] ],
    pluginName: 'snyk-nodejs-lockfile-parser',
    policies: 2,
    packageManager: [ 'npm', 'npm' ],
    packageName: 'biz-ops-runbooks',
    packageVersion: '1.0.0',
    package: 'biz-ops-runbooks@1.0.0',
    depGraph: true,
    isDocker: false,
    'vulns-pre-policy': 1,
    vulns: 1,
    answers: [ [Object] ],
    'add-snyk-test': false,
    'add-snyk-protect': undefined,
    monitorGraph: true,
    targetBranch: 'upgrade'
  },
  version: '1.272.0',
  os: 'macOS Mojave',
  nodeVersion: 'v12.13.1',
  id: '035dbac64666f8557efae9562d31d8c4e6042fee',
  ci: false,
  durationMs: 160083
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +8s
  snyk request body size: 1180 +0ms
  snyk gzipped request body size: 656 +0ms
  snyk not using proxy +0ms
- Analyzing npm dependencies for /Users/wheresrhys/Projects/biz-ops-runbooks/package-lock.json
```
